export const UPDATE_SCREEN_NAME = 'UPDATE_SCREEN_NAME';
export const STORE_SEARCH_DATA = 'STORE_SEARCH_DATA';
export const SET_USER_PRESSED_DATA = 'SET_USER_PRESSED_DATA';
export const STORE_CURRENT_IMAGE = 'STORE_CURRENT_IMAGE';